openapi: 3.0.0
info:
  # Basic Markdown works in the top level description, so using it to give some basic guidelines.
  # Note this is the only "text" that gets the Markdown treatment.
  description: |
    ## Confluent Metadata v2.0 API - Swagger UI
  version: "v2"
  title: MDS API

servers:
  - url: /calculator

paths:
  /add:
    summary: Authorize operations against resourceType for a given user.  Callable by Admins+User.
    operationId: authorize
    parameters:
      - in: header
        name: X-Request-Id
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          example:
            target_principal: User:abc12
            actions:
              -resource_name: crn://confluent.cloud/schema-registry=lsrc-ab123/subject=test_subject
              -operation: READ
          schema:
            $ref: '#/components/schemas/AuthorizeRequest'

    responses:
      '200':
        description: Authorization proccessed
        content:
          application/json: